# Generated by Django 5.0.4 on 2024-05-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneline', '0003_statustaxatline_label_linephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linephone',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, related_name='line_phones', to='phoneline.label'),
        ),
    ]
