# Generated by Django 5.0.4 on 2024-05-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneline', '0004_alter_linephone_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linephone',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='line_phones', to='phoneline.label'),
        ),
    ]
